<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ExapiPackage Condition="'$(ExapiPackage)' == ''">$(MSBuildProjectDirectory)\Resources</ExapiPackage>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Compile Remove="AutoExile.Replay\**" />
    <Compile Remove="USER BRANCH\**" />
    <EmbeddedResource Remove="USER BRANCH\**" />
    <None Remove="USER BRANCH\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\uniqueArtMapping.json">
      <LogicalName>uniqueArtMapping.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="WebServer\wwwroot\index.html">
      <LogicalName>webui.index.html</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.provider.winsqlite3" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ExileCore">
      <HintPath>$(ExapiPackage)\ExileCore.dll</HintPath>
    </Reference>
    <Reference Include="GameOffsets">
      <HintPath>$(ExapiPackage)\GameOffsets.dll</HintPath>
    </Reference>
    <Reference Include="ImGui.NET">
      <HintPath>$(ExapiPackage)\ImGui.NET.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX">
      <HintPath>$(ExapiPackage)\SharpDX.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX.Mathematics">
      <HintPath>$(ExapiPackage)\SharpDX.Mathematics.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
